/**
 * The Leipzig–Jakarta list (Tadmor, Haspelmath & Taylor 2010): the 100 meanings
 * found to be most resistant to borrowing across the World Loanword Database.
 * Sixteen items are already fixed by the Manual (water, you, I, big, one, he,
 * fish, yesterday, wind, not, blow, see, salt, small, stone → rock, in → the
 * inessive case); the remaining 84 are derived here, in list order, from the
 * queue state the Manual leaves behind. No entry has a manual decree: what the
 * procedure yields is the word.
 */
import type { Concept } from "./synthesize";

export const LEIPZIG_JAKARTA: Concept[] = [
  { id: "fire", gloss: "fire", pos: "noun", domain: "landscape",
    sources: { fi: "tuli", et: "tuli", lv: "uguns", lt: "ugnis", pl: "ogień", ru: "огонь", sv: "eld", da: "ild", de: "Feuer" } },
  { id: "nose", gloss: "nose", pos: "noun", domain: "body",
    sources: { fi: "nenä", et: "nina", lv: "deguns", lt: "nosis", pl: "nos", ru: "нос", sv: "näsa", da: "næse", de: "Nase" } },
  { id: "go", gloss: "to go", pos: "verb", domain: "motion",
    sources: { fi: "mennä", et: "minema", lv: "iet", lt: "eiti", pl: "iść", ru: "идти", sv: "gå", da: "gå", de: "gehen" } },
  { id: "mouth", gloss: "mouth", pos: "noun", domain: "body",
    sources: { fi: "suu", et: "suu", lv: "mute", lt: "burna", pl: "usta", ru: "рот", sv: "mun", da: "mund", de: "Mund" } },
  { id: "tongue", gloss: "tongue", pos: "noun", domain: "body",
    sources: { fi: "kieli", et: "keel", lv: "mēle", lt: "liežuvis", pl: "język", ru: "язык", sv: "tunga", da: "tunge", de: "Zunge" } },
  { id: "blood", gloss: "blood", pos: "noun", domain: "body",
    sources: { fi: "veri", et: "veri", lv: "asinis", lt: "kraujas", pl: "krew", ru: "кровь", sv: "blod", da: "blod", de: "Blut" } },
  { id: "bone", gloss: "bone", pos: "noun", domain: "body",
    sources: { fi: "luu", et: "luu", lv: "kauls", lt: "kaulas", pl: "kość", ru: "кость", sv: "ben", da: "knogle", de: "Knochen" } },
  { id: "root", gloss: "root", pos: "noun", domain: "forest",
    sources: { fi: "juuri", et: "juur", lv: "sakne", lt: "šaknis", pl: "korzeń", ru: "корень", sv: "rot", da: "rod", de: "Wurzel" } },
  { id: "come", gloss: "to come", pos: "verb", domain: "motion",
    sources: { fi: "tulla", et: "tulema", lv: "nākt", lt: "ateiti", pl: "przychodzić", ru: "приходить", sv: "komma", da: "komme", de: "kommen" } },
  { id: "breast", gloss: "breast, chest", pos: "noun", domain: "body",
    sources: { fi: "rinta", et: "rind", lv: "krūts", lt: "krūtis", pl: "pierś", ru: "грудь", sv: "bröst", da: "bryst", de: "Brust" } },
  { id: "rain", gloss: "rain", pos: "noun", domain: "weather",
    sources: { fi: "sade", et: "vihm", lv: "lietus", lt: "lietus", pl: "deszcz", ru: "дождь", sv: "regn", da: "regn", de: "Regen" } },
  { id: "name", gloss: "name", pos: "noun", domain: "abstract",
    sources: { fi: "nimi", et: "nimi", lv: "vārds", lt: "vardas", pl: "imię", ru: "имя", sv: "namn", da: "navn", de: "Name" } },
  { id: "louse", gloss: "louse", pos: "noun", domain: "farm",
    sources: { fi: "täi", et: "täi", lv: "uts", lt: "utėlė", pl: "wesz", ru: "вошь", sv: "lus", da: "lus", de: "Laus" } },
  { id: "wing", gloss: "wing", pos: "noun", domain: "body",
    sources: { fi: "siipi", et: "tiib", lv: "spārns", lt: "sparnas", pl: "skrzydło", ru: "крыло", sv: "vinge", da: "vinge", de: "Flügel" } },
  { id: "meat", gloss: "meat, flesh", pos: "noun", domain: "farm",
    sources: { fi: "liha", et: "liha", lv: "gaļa", lt: "mėsa", pl: "mięso", ru: "мясо", sv: "kött", da: "kød", de: "Fleisch" } },
  { id: "hand", gloss: "hand, arm", pos: "noun", domain: "body",
    sources: { fi: "käsi", et: "käsi", lv: "roka", lt: "ranka", pl: "ręka", ru: "рука", sv: "hand", da: "hånd", de: "Hand" } },
  { id: "fly", gloss: "fly (insect)", pos: "noun", domain: "farm",
    sources: { fi: "kärpänen", et: "kärbes", lv: "muša", lt: "musė", pl: "mucha", ru: "муха", sv: "fluga", da: "flue", de: "Fliege" } },
  { id: "night", gloss: "night", pos: "noun", domain: "season",
    sources: { fi: "yö", et: "öö", lv: "nakts", lt: "naktis", pl: "noc", ru: "ночь", sv: "natt", da: "nat", de: "Nacht" } },
  { id: "ear", gloss: "ear", pos: "noun", domain: "body",
    sources: { fi: "korva", et: "kõrv", lv: "auss", lt: "ausis", pl: "ucho", ru: "ухо", sv: "öra", da: "øre", de: "Ohr" } },
  { id: "neck", gloss: "neck", pos: "noun", domain: "body",
    sources: { fi: "kaula", et: "kael", lv: "kakls", lt: "kaklas", pl: "szyja", ru: "шея", sv: "hals", da: "hals", de: "Hals" } },
  { id: "far", gloss: "far, distant", pos: "adj", domain: "quality",
    sources: { fi: "kaukainen", et: "kauge", lv: "tāls", lt: "tolimas", pl: "daleki", ru: "далёкий", sv: "fjärran", da: "fjern", de: "fern" } },
  { id: "make", gloss: "to do, to make", pos: "verb", domain: "action",
    sources: { fi: "tehdä", et: "tegema", lv: "darīt", lt: "daryti", pl: "robić", ru: "делать", sv: "göra", da: "gøre", de: "machen" } },
  { id: "house", gloss: "house", pos: "noun", domain: "town",
    sources: { fi: "talo", et: "maja", lv: "māja", lt: "namas", pl: "dom", ru: "дом", sv: "hus", da: "hus", de: "Haus" } },
  { id: "bitter", gloss: "bitter", pos: "adj", domain: "quality",
    sources: { fi: "karvas", et: "kibe", lv: "rūgts", lt: "kartus", pl: "gorzki", ru: "горький", sv: "bitter", da: "bitter", de: "bitter" } },
  { id: "say", gloss: "to say", pos: "verb", domain: "action",
    sources: { fi: "sanoa", et: "ütlema", lv: "sacīt", lt: "sakyti", pl: "mówić", ru: "сказать", sv: "säga", da: "sige", de: "sagen" } },
  { id: "tooth", gloss: "tooth", pos: "noun", domain: "body",
    sources: { fi: "hammas", et: "hammas", lv: "zobs", lt: "dantis", pl: "ząb", ru: "зуб", sv: "tand", da: "tand", de: "Zahn" } },
  { id: "hair", gloss: "hair", pos: "noun", domain: "body",
    sources: { fi: "hius", et: "juus", lv: "mats", lt: "plaukas", pl: "włos", ru: "волос", sv: "hår", da: "hår", de: "Haar" } },
  { id: "who", gloss: "who?", pos: "pron",
    sources: { fi: "kuka", et: "kes", lv: "kas", lt: "kas", pl: "kto", ru: "кто", sv: "vem", da: "hvem", de: "wer" } },
  { id: "hit", gloss: "to hit, to beat", pos: "verb", domain: "action",
    sources: { fi: "lyödä", et: "lööma", lv: "sist", lt: "mušti", pl: "bić", ru: "бить", sv: "slå", da: "slå", de: "schlagen" } },
  { id: "leg", gloss: "leg, foot", pos: "noun", domain: "body",
    sources: { fi: "jalka", et: "jalg", lv: "kāja", lt: "koja", pl: "noga", ru: "нога", sv: "ben", da: "ben", de: "Bein" } },
  { id: "horn", gloss: "horn", pos: "noun", domain: "body",
    sources: { fi: "sarvi", et: "sarv", lv: "rags", lt: "ragas", pl: "róg", ru: "рог", sv: "horn", da: "horn", de: "Horn" } },
  { id: "this", gloss: "this", pos: "pron",
    sources: { fi: "tämä", et: "see", lv: "šis", lt: "šis", pl: "ten", ru: "этот", sv: "denna", da: "denne", de: "dieser" } },
  { id: "drink", gloss: "to drink", pos: "verb", domain: "action",
    sources: { fi: "juoda", et: "jooma", lv: "dzert", lt: "gerti", pl: "pić", ru: "пить", sv: "dricka", da: "drikke", de: "trinken" } },
  { id: "black", gloss: "black", pos: "adj", domain: "colour",
    sources: { fi: "musta", et: "must", lv: "melns", lt: "juodas", pl: "czarny", ru: "чёрный", sv: "svart", da: "sort", de: "schwarz" } },
  { id: "navel", gloss: "navel", pos: "noun", domain: "body",
    sources: { fi: "napa", et: "naba", lv: "naba", lt: "bamba", pl: "pępek", ru: "пуп", sv: "navel", da: "navle", de: "Nabel" } },
  { id: "stand", gloss: "to stand", pos: "verb", domain: "action",
    sources: { fi: "seistä", et: "seisma", lv: "stāvēt", lt: "stovėti", pl: "stać", ru: "стоять", sv: "stå", da: "stå", de: "stehen" } },
  { id: "bite", gloss: "to bite", pos: "verb", domain: "action",
    sources: { fi: "purra", et: "hammustama", lv: "kost", lt: "kąsti", pl: "gryźć", ru: "кусать", sv: "bita", da: "bide", de: "beißen" } },
  { id: "back", gloss: "back (body)", pos: "noun", domain: "body",
    sources: { fi: "selkä", et: "selg", lv: "mugura", lt: "nugara", pl: "plecy", ru: "спина", sv: "rygg", da: "ryg", de: "Rücken" } },
  { id: "smoke", gloss: "smoke", pos: "noun", domain: "weather",
    sources: { fi: "savu", et: "suits", lv: "dūmi", lt: "dūmai", pl: "dym", ru: "дым", sv: "rök", da: "røg", de: "Rauch" } },
  { id: "what", gloss: "what?", pos: "pron",
    sources: { fi: "mikä", et: "mis", lv: "kas", lt: "kas", pl: "co", ru: "что", sv: "vad", da: "hvad", de: "was" } },
  { id: "child", gloss: "child", pos: "noun", domain: "kinship",
    sources: { fi: "lapsi", et: "laps", lv: "bērns", lt: "vaikas", pl: "dziecko", ru: "ребёнок", sv: "barn", da: "barn", de: "Kind" } },
  { id: "egg", gloss: "egg", pos: "noun", domain: "farm",
    sources: { fi: "muna", et: "muna", lv: "ola", lt: "kiaušinis", pl: "jajko", ru: "яйцо", sv: "ägg", da: "æg", de: "Ei" } },
  { id: "give", gloss: "to give", pos: "verb", domain: "action",
    sources: { fi: "antaa", et: "andma", lv: "dot", lt: "duoti", pl: "dać", ru: "дать", sv: "ge", da: "give", de: "geben" } },
  { id: "new", gloss: "new", pos: "adj", domain: "quality",
    sources: { fi: "uusi", et: "uus", lv: "jauns", lt: "naujas", pl: "nowy", ru: "новый", sv: "ny", da: "ny", de: "neu" } },
  { id: "burn", gloss: "to burn (intr.)", pos: "verb", domain: "action",
    sources: { fi: "palaa", et: "põlema", lv: "degt", lt: "degti", pl: "płonąć", ru: "гореть", sv: "brinna", da: "brænde", de: "brennen" } },
  { id: "good", gloss: "good", pos: "adj", domain: "quality",
    sources: { fi: "hyvä", et: "hea", lv: "labs", lt: "geras", pl: "dobry", ru: "хороший", sv: "god", da: "god", de: "gut" } },
  { id: "know", gloss: "to know", pos: "verb", domain: "action",
    sources: { fi: "tietää", et: "teadma", lv: "zināt", lt: "žinoti", pl: "wiedzieć", ru: "знать", sv: "veta", da: "vide", de: "wissen" } },
  { id: "knee", gloss: "knee", pos: "noun", domain: "body",
    sources: { fi: "polvi", et: "põlv", lv: "celis", lt: "kelis", pl: "kolano", ru: "колено", sv: "knä", da: "knæ", de: "Knie" } },
  { id: "sand", gloss: "sand", pos: "noun", domain: "landscape",
    sources: { fi: "hiekka", et: "liiv", lv: "smiltis", lt: "smėlis", pl: "piasek", ru: "песок", sv: "sand", da: "sand", de: "Sand" } },
  { id: "laugh", gloss: "to laugh", pos: "verb", domain: "emotion",
    sources: { fi: "nauraa", et: "naerma", lv: "smieties", lt: "juoktis", pl: "śmiać", ru: "смеяться", sv: "skratta", da: "le", de: "lachen" } },
  { id: "hear", gloss: "to hear", pos: "verb", domain: "action",
    sources: { fi: "kuulla", et: "kuulma", lv: "dzirdēt", lt: "girdėti", pl: "słyszeć", ru: "слышать", sv: "höra", da: "høre", de: "hören" } },
  { id: "soil", gloss: "soil, earth", pos: "noun", domain: "landscape",
    sources: { fi: "maa", et: "muld", lv: "zeme", lt: "žemė", pl: "ziemia", ru: "земля", sv: "jord", da: "jord", de: "Erde" } },
  { id: "leaf", gloss: "leaf", pos: "noun", domain: "forest",
    sources: { fi: "lehti", et: "leht", lv: "lapa", lt: "lapas", pl: "liść", ru: "лист", sv: "löv", da: "blad", de: "Blatt" } },
  { id: "red", gloss: "red", pos: "adj", domain: "colour",
    sources: { fi: "punainen", et: "punane", lv: "sarkans", lt: "raudonas", pl: "czerwony", ru: "красный", sv: "röd", da: "rød", de: "rot" } },
  { id: "liver", gloss: "liver", pos: "noun", domain: "body",
    sources: { fi: "maksa", et: "maks", lv: "aknas", lt: "kepenys", pl: "wątroba", ru: "печень", sv: "lever", da: "lever", de: "Leber" } },
  { id: "hide", gloss: "to hide", pos: "verb", domain: "action",
    sources: { fi: "piilottaa", et: "peitma", lv: "slēpt", lt: "slėpti", pl: "chować", ru: "прятать", sv: "gömma", da: "gemme", de: "verstecken" } },
  { id: "skin", gloss: "skin, hide", pos: "noun", domain: "body",
    sources: { fi: "iho", et: "nahk", lv: "āda", lt: "oda", pl: "skóra", ru: "кожа", sv: "hud", da: "hud", de: "Haut" } },
  { id: "suck", gloss: "to suck", pos: "verb", domain: "action",
    sources: { fi: "imeä", et: "imema", lv: "sūkt", lt: "čiulpti", pl: "ssać", ru: "сосать", sv: "suga", da: "suge", de: "saugen" } },
  { id: "carry", gloss: "to carry", pos: "verb", domain: "action",
    sources: { fi: "kantaa", et: "kandma", lv: "nest", lt: "nešti", pl: "nieść", ru: "нести", sv: "bära", da: "bære", de: "tragen" } },
  { id: "ant", gloss: "ant", pos: "noun", domain: "forest",
    sources: { fi: "muurahainen", et: "sipelgas", lv: "skudra", lt: "skruzdėlė", pl: "mrówka", ru: "муравей", sv: "myra", da: "myre", de: "Ameise" } },
  { id: "heavy", gloss: "heavy", pos: "adj", domain: "quality",
    sources: { fi: "painava", et: "raske", lv: "smags", lt: "sunkus", pl: "ciężki", ru: "тяжёлый", sv: "tung", da: "tung", de: "schwer" } },
  { id: "take", gloss: "to take", pos: "verb", domain: "action",
    sources: { fi: "ottaa", et: "võtma", lv: "ņemt", lt: "imti", pl: "brać", ru: "брать", sv: "ta", da: "tage", de: "nehmen" } },
  { id: "old", gloss: "old", pos: "adj", domain: "quality",
    sources: { fi: "vanha", et: "vana", lv: "vecs", lt: "senas", pl: "stary", ru: "старый", sv: "gammal", da: "gammel", de: "alt" } },
  { id: "eat", gloss: "to eat", pos: "verb", domain: "action",
    sources: { fi: "syödä", et: "sööma", lv: "ēst", lt: "valgyti", pl: "jeść", ru: "есть", sv: "äta", da: "spise", de: "essen" } },
  { id: "thigh", gloss: "thigh", pos: "noun", domain: "body",
    sources: { fi: "reisi", et: "reis", lv: "ciska", lt: "šlaunis", pl: "udo", ru: "бедро", sv: "lår", da: "lår", de: "Schenkel" } },
  { id: "thick", gloss: "thick", pos: "adj", domain: "quality",
    sources: { fi: "paksu", et: "paks", lv: "biezs", lt: "storas", pl: "gruby", ru: "толстый", sv: "tjock", da: "tyk", de: "dick" } },
  { id: "long", gloss: "long", pos: "adj", domain: "quality",
    sources: { fi: "pitkä", et: "pikk", lv: "garš", lt: "ilgas", pl: "długi", ru: "длинный", sv: "lång", da: "lang", de: "lang" } },
  { id: "wood", gloss: "wood (material)", pos: "noun", domain: "forest",
    sources: { fi: "puu", et: "puu", lv: "koks", lt: "medis", pl: "drewno", ru: "дерево", sv: "trä", da: "træ", de: "Holz" } },
  { id: "run", gloss: "to run", pos: "verb", domain: "motion",
    sources: { fi: "juosta", et: "jooksma", lv: "skriet", lt: "bėgti", pl: "biec", ru: "бежать", sv: "springa", da: "løbe", de: "laufen" } },
  { id: "fall", gloss: "to fall", pos: "verb", domain: "motion",
    sources: { fi: "pudota", et: "kukkuma", lv: "krist", lt: "kristi", pl: "padać", ru: "падать", sv: "falla", da: "falde", de: "fallen" } },
  { id: "eye", gloss: "eye", pos: "noun", domain: "body",
    sources: { fi: "silmä", et: "silm", lv: "acs", lt: "akis", pl: "oko", ru: "глаз", sv: "öga", da: "øje", de: "Auge" } },
  { id: "ash", gloss: "ash", pos: "noun", domain: "landscape",
    sources: { fi: "tuhka", et: "tuhk", lv: "pelni", lt: "pelenai", pl: "popiół", ru: "пепел", sv: "aska", da: "aske", de: "Asche" } },
  { id: "tail", gloss: "tail", pos: "noun", domain: "body",
    sources: { fi: "häntä", et: "saba", lv: "aste", lt: "uodega", pl: "ogon", ru: "хвост", sv: "svans", da: "hale", de: "Schwanz" } },
  { id: "dog", gloss: "dog", pos: "noun", domain: "farm",
    sources: { fi: "koira", et: "koer", lv: "suns", lt: "šuo", pl: "pies", ru: "собака", sv: "hund", da: "hund", de: "Hund" } },
  { id: "cry", gloss: "to cry, to weep", pos: "verb", domain: "emotion",
    sources: { fi: "itkeä", et: "nutma", lv: "raudāt", lt: "verkti", pl: "płakać", ru: "плакать", sv: "gråta", da: "græde", de: "weinen" } },
  { id: "tie", gloss: "to tie, to bind", pos: "verb", domain: "action",
    sources: { fi: "sitoa", et: "siduma", lv: "siet", lt: "sieti", pl: "wiązać", ru: "вязать", sv: "binda", da: "binde", de: "binden" } },
  { id: "sweet", gloss: "sweet", pos: "adj", domain: "quality",
    sources: { fi: "makea", et: "magus", lv: "salds", lt: "saldus", pl: "słodki", ru: "сладкий", sv: "söt", da: "sød", de: "süß" } },
  { id: "rope", gloss: "rope", pos: "noun", domain: "tool",
    sources: { fi: "köysi", et: "köis", lv: "virve", lt: "virvė", pl: "lina", ru: "верёвка", sv: "rep", da: "reb", de: "Seil" } },
  { id: "shadow", gloss: "shade, shadow", pos: "noun", domain: "weather",
    sources: { fi: "varjo", et: "vari", lv: "ēna", lt: "šešėlis", pl: "cień", ru: "тень", sv: "skugga", da: "skygge", de: "Schatten" } },
  { id: "bird", gloss: "bird", pos: "noun", domain: "forest",
    sources: { fi: "lintu", et: "lind", lv: "putns", lt: "paukštis", pl: "ptak", ru: "птица", sv: "fågel", da: "fugl", de: "Vogel" } },
  { id: "wide", gloss: "wide, broad", pos: "adj", domain: "quality",
    sources: { fi: "leveä", et: "lai", lv: "plats", lt: "platus", pl: "szeroki", ru: "широкий", sv: "bred", da: "bred", de: "breit" } },
  { id: "star", gloss: "star", pos: "noun", domain: "weather",
    sources: { fi: "tähti", et: "täht", lv: "zvaigzne", lt: "žvaigždė", pl: "gwiazda", ru: "звезда", sv: "stjärna", da: "stjerne", de: "Stern" } },
  { id: "hard", gloss: "hard", pos: "adj", domain: "quality",
    sources: { fi: "kova", et: "kõva", lv: "ciets", lt: "kietas", pl: "twardy", ru: "твёрдый", sv: "hård", da: "hård", de: "hart" } },
  { id: "grind", gloss: "to grind, to crush", pos: "verb", domain: "action",
    sources: { fi: "jauhaa", et: "jahvatama", lv: "malt", lt: "malti", pl: "mleć", ru: "молоть", sv: "mala", da: "male", de: "mahlen" } }
];

/** Leipzig–Jakarta meanings the Manual already fixes, mapped to their lexicon ids. */
export const LEIPZIG_JAKARTA_IN_MANUAL: Record<string, string> = {
  water: "water", you: "you", I: "I", big: "big", one: "one", "he/she": "he", fish: "fish", yesterday: "yesterday",
  wind: "wind", not: "not", blow: "blow", see: "see", salt: "salt", small: "small", "stone/rock": "rock", in: "(inessive case -se)"
};
